#!/usr/bin/env python3
# CSSPrefixer
# Copyright 2010 MyFreeWeb <me@myfreeweb.ru>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


if __name__ == '__main__':
    from optparse import OptionParser
    from cssprefixer import process

    parser = OptionParser()
    parser.add_option('-m', '--minify',
        dest='minify',
        default=False,
        action='store_true'
    )
    parser.add_option('-d', '--debug',
        dest='debug',
        default=False,
        action='store_true'
    )

    options, args = parser.parse_args()

    for fn in args:
        print(process(open(fn, 'r').read(), options.debug, options.minify))

